BEGIN;

CREATE TABLE IF NOT EXISTS public.page_views (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  path TEXT NOT NULL,
  content_type TEXT NOT NULL,
  content_slug TEXT,
  session_id TEXT,
  referrer TEXT,
  user_agent TEXT,
  viewed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_page_views_viewed_at ON public.page_views(viewed_at DESC);
CREATE INDEX IF NOT EXISTS idx_page_views_content_type ON public.page_views(content_type);
CREATE INDEX IF NOT EXISTS idx_page_views_content_slug ON public.page_views(content_slug);
CREATE INDEX IF NOT EXISTS idx_page_views_session_id ON public.page_views(session_id);

ALTER TABLE IF EXISTS public.page_views ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can insert page views" ON public.page_views;
DROP POLICY IF EXISTS "Authenticated users can read page views" ON public.page_views;
DROP POLICY IF EXISTS "Authenticated users can manage page views" ON public.page_views;

CREATE POLICY "Anyone can insert page views"
ON public.page_views
FOR INSERT
TO anon, authenticated
WITH CHECK (true);

CREATE POLICY "Authenticated users can read page views"
ON public.page_views
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Authenticated users can manage page views"
ON public.page_views
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

COMMIT;
