-- Affiliate tables for links, click tracking, conversions, and placements
-- Run this in Supabase SQL Editor after your locations / regions tables exist.

BEGIN;

CREATE TABLE IF NOT EXISTS affiliate_links (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  location_id BIGINT REFERENCES locations(id) ON DELETE CASCADE,
  region_id BIGINT REFERENCES regions(id) ON DELETE CASCADE,
  provider TEXT NOT NULL CHECK (provider IN ('agoda', 'booking', 'klook', 'kkday', 'trip', 'others')),
  link_type TEXT NOT NULL CHECK (link_type IN ('hotel', 'ticket', 'tour', 'transport', 'food', 'insurance', 'sim', 'others')),
  url TEXT NOT NULL,
  title TEXT,
  description TEXT,
  commission_rate DECIMAL(5,2) DEFAULT 0.00,
  is_active BOOLEAN DEFAULT TRUE,
  clicks INTEGER DEFAULT 0,
  conversions INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS affiliate_clicks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  affiliate_link_id BIGINT NOT NULL REFERENCES affiliate_links(id) ON DELETE CASCADE,
  session_id TEXT,
  ip_address TEXT,
  user_agent TEXT,
  referrer TEXT,
  clicked_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS affiliate_conversions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  affiliate_link_id BIGINT NOT NULL REFERENCES affiliate_links(id) ON DELETE CASCADE,
  transaction_id TEXT,
  amount DECIMAL(10,2),
  commission DECIMAL(10,2),
  currency TEXT DEFAULT 'USD',
  status TEXT CHECK (status IN ('pending', 'confirmed', 'paid', 'cancelled')),
  converted_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ad_placements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_type TEXT NOT NULL CHECK (page_type IN ('location_detail', 'region_list', 'home', 'search')),
  position TEXT NOT NULL CHECK (position IN ('top', 'bottom', 'sidebar', 'inline')),
  provider TEXT NOT NULL,
  code TEXT,
  is_active BOOLEAN DEFAULT TRUE,
  priority INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_affiliate_links_location ON affiliate_links(location_id);
CREATE INDEX IF NOT EXISTS idx_affiliate_links_region ON affiliate_links(region_id);
CREATE INDEX IF NOT EXISTS idx_affiliate_links_provider ON affiliate_links(provider);
CREATE INDEX IF NOT EXISTS idx_affiliate_clicks_link ON affiliate_clicks(affiliate_link_id);
CREATE INDEX IF NOT EXISTS idx_affiliate_clicks_time ON affiliate_clicks(clicked_at);
CREATE INDEX IF NOT EXISTS idx_affiliate_conversions_link ON affiliate_conversions(affiliate_link_id);
CREATE INDEX IF NOT EXISTS idx_affiliate_conversions_status ON affiliate_conversions(status);
CREATE INDEX IF NOT EXISTS idx_ad_placements_page ON ad_placements(page_type, position);

ALTER TABLE affiliate_links ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE ad_placements ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

CREATE OR REPLACE FUNCTION update_affiliate_links_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_update_affiliate_links_updated_at ON affiliate_links;
CREATE TRIGGER trigger_update_affiliate_links_updated_at
BEFORE UPDATE ON affiliate_links
FOR EACH ROW
EXECUTE FUNCTION update_affiliate_links_updated_at();

CREATE OR REPLACE FUNCTION update_ad_placements_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_update_ad_placements_updated_at ON ad_placements;
CREATE TRIGGER trigger_update_ad_placements_updated_at
BEFORE UPDATE ON ad_placements
FOR EACH ROW
EXECUTE FUNCTION update_ad_placements_updated_at();

INSERT INTO ad_placements (page_type, position, provider, code, priority)
VALUES
  ('location_detail', 'bottom', 'agoda', 'hotel_booking_card', 10),
  ('location_detail', 'sidebar', 'klook', 'tour_widget', 20),
  ('region_list', 'top', 'booking', 'banner_728x90', 5),
  ('home', 'inline', 'others', 'newsletter_signup', 30)
ON CONFLICT DO NOTHING;

COMMIT;
