-- 2026-10-02 JnQ Journey analytics + database hygiene

do $$
declare
  tbl text;
begin
  foreach tbl in array array[
    'affiliate_clicks',
    'affiliate_conversions',
    'guide_budget_sync_nonces',
    'guide_english_sync_queue',
    'locations_backup_before_r2',
    'note_english_sync_queue',
    'page_views',
    'spot_description_optimization_backup',
    'spot_description_optimization_queue',
    'spot_publication_sync',
    'travel_package_internal',
    'travel_package_option_internal'
  ]
  loop
    execute format('drop policy if exists "Deny direct client access" on public.%I', tbl);
    execute format(
      'create policy "Deny direct client access" on public.%I for all to anon, authenticated using (false) with check (false)',
      tbl
    );
  end loop;
end $$;

alter table public.guide_budget_snapshots
  drop constraint if exists guide_budget_snapshots_source_source_event_key_snapshot_ver_key;

alter table public.locations_backup_before_r2
  add constraint locations_backup_before_r2_pkey primary key (id);

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_name text not null,
  path text,
  session_id text,
  device_type text,
  package_id bigint,
  option_id bigint,
  source_code text,
  params jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now()
);

create index if not exists analytics_events_occurred_at_idx
  on public.analytics_events (occurred_at desc);
create index if not exists analytics_events_event_name_idx
  on public.analytics_events (event_name);
create index if not exists analytics_events_package_option_idx
  on public.analytics_events (package_id, option_id, occurred_at desc);

alter table public.analytics_events enable row level security;
drop policy if exists "Deny direct client access" on public.analytics_events;
create policy "Deny direct client access"
on public.analytics_events
for all
to anon, authenticated
using (false)
with check (false);
