-- JnQ Journey travel package content model.
-- Run once in the Supabase SQL Editor, then verify RLS before publishing.

BEGIN;

CREATE TABLE IF NOT EXISTS public.travel_packages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug text NOT NULL UNIQUE,
  title_zh text NOT NULL,
  title_en text,
  destination text,
  region_id bigint REFERENCES public.regions(id) ON DELETE SET NULL,
  duration text,
  short_description text,
  full_description text,
  cover_image text,
  gallery jsonb NOT NULL DEFAULT '[]'::jsonb,
  video_url text,
  highlights jsonb NOT NULL DEFAULT '[]'::jsonb,
  suitable_for jsonb NOT NULL DEFAULT '[]'::jsonb,
  itinerary_days jsonb NOT NULL DEFAULT '[]'::jsonb,
  included_items jsonb NOT NULL DEFAULT '[]'::jsonb,
  excluded_items jsonb NOT NULL DEFAULT '[]'::jsonb,
  notes jsonb NOT NULL DEFAULT '[]'::jsonb,
  price_display text,
  price_note text,
  whatsapp_message text,
  source_code text,
  status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published', 'archived')),
  featured boolean NOT NULL DEFAULT false,
  sort_order integer NOT NULL DEFAULT 0,
  seo_title text,
  seo_description text,
  canonical_url text,
  related_location_ids bigint[] NOT NULL DEFAULT '{}',
  related_guide_slugs text[] NOT NULL DEFAULT '{}',
  related_note_slugs text[] NOT NULL DEFAULT '{}',
  affiliate_link_ids bigint[] NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  published_at timestamptz
);

CREATE INDEX IF NOT EXISTS travel_packages_public_idx
  ON public.travel_packages (status, featured DESC, sort_order, published_at DESC);
CREATE INDEX IF NOT EXISTS travel_packages_region_idx ON public.travel_packages (region_id);

ALTER TABLE public.travel_packages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public can read published travel packages" ON public.travel_packages;
CREATE POLICY "Public can read published travel packages"
ON public.travel_packages FOR SELECT
USING (status = 'published');

DROP POLICY IF EXISTS "Authenticated can manage travel packages" ON public.travel_packages;
CREATE POLICY "Authenticated can manage travel packages"
ON public.travel_packages FOR ALL TO authenticated
USING (true) WITH CHECK (true);

INSERT INTO public.travel_packages (
  slug, title_zh, title_en, destination, duration, short_description,
  price_note, source_code, status, featured, sort_order
)
VALUES (
  'batam-3d2n',
  '巴淡岛 3天2夜旅游配套',
  'Batam 3D2N Travel Package',
  'Batam',
  '3天2夜',
  '适合情侣、家庭及朋友团体，可查询不同出发日期、人数与码头安排。',
  '最新价格会根据出发日期、人数、房型及出发码头调整，请通过 WhatsApp 查询。',
  'JNQ-BATAM-PACKAGE',
  'draft',
  true,
  10
)
ON CONFLICT (slug) DO NOTHING;

COMMIT;
