BEGIN;

CREATE TABLE IF NOT EXISTS public.page_views (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  path TEXT NOT NULL,
  content_type TEXT NOT NULL,
  content_slug TEXT,
  session_id TEXT,
  referrer TEXT,
  user_agent TEXT,
  viewed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_page_views_viewed_at ON public.page_views(viewed_at DESC);
CREATE INDEX IF NOT EXISTS idx_page_views_content_type ON public.page_views(content_type);
CREATE INDEX IF NOT EXISTS idx_page_views_content_slug ON public.page_views(content_slug);
CREATE INDEX IF NOT EXISTS idx_page_views_session_id ON public.page_views(session_id);

ALTER TABLE IF EXISTS public.page_views ENABLE ROW LEVEL SECURITY;

-- Page views are written and read only through server-side routes using the
-- Supabase service role. Keep anon/authenticated clients away from raw
-- analytics rows so bot filtering and production-host validation cannot be
-- bypassed from the browser.
DROP POLICY IF EXISTS "Anyone can insert page views" ON public.page_views;
DROP POLICY IF EXISTS "Authenticated users can read page views" ON public.page_views;
DROP POLICY IF EXISTS "Authenticated users can manage page views" ON public.page_views;

COMMIT;
