-- 1. Ensure regions table exists
CREATE TABLE IF NOT EXISTS regions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  code TEXT,
  parent_id BIGINT REFERENCES regions(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Ensure locations table has region_id
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'locations' AND column_name = 'region_id') THEN
        ALTER TABLE locations ADD COLUMN region_id BIGINT REFERENCES regions(id);
    END IF;
END $$;

-- 3. Enable RLS but ensure policies allow access
ALTER TABLE regions ENABLE ROW LEVEL SECURITY;

-- Drop existing policies to avoid conflicts/errors
DROP POLICY IF EXISTS "Public regions are viewable by everyone" ON regions;
DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON regions;
DROP POLICY IF EXISTS "Enable update for authenticated users only" ON regions;
DROP POLICY IF EXISTS "Enable delete for authenticated users only" ON regions;

-- Re-create Policies
CREATE POLICY "Public regions are viewable by everyone" 
ON regions FOR SELECT 
USING (true);

CREATE POLICY "Enable insert for authenticated users only" 
ON regions FOR INSERT 
WITH CHECK (true); -- Relaxed for development/demo

CREATE POLICY "Enable update for authenticated users only" 
ON regions FOR UPDATE 
USING (true);

CREATE POLICY "Enable delete for authenticated users only" 
ON regions FOR DELETE 
USING (true);

-- 4. Check if data exists, if not, insert defaults
INSERT INTO regions (name, code)
SELECT 'Johor', 'JHR'
WHERE NOT EXISTS (SELECT 1 FROM regions WHERE name = 'Johor');

INSERT INTO regions (name, code)
SELECT 'Kuala Lumpur', 'KUL'
WHERE NOT EXISTS (SELECT 1 FROM regions WHERE name = 'Kuala Lumpur');

INSERT INTO regions (name, code)
SELECT 'Penang', 'PNG'
WHERE NOT EXISTS (SELECT 1 FROM regions WHERE name = 'Penang');

-- Add other states as needed...
