
-- Create regions table
CREATE TABLE IF NOT EXISTS regions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  code TEXT, -- Optional short code (e.g. 'JHR' for Johor)
  parent_id BIGINT REFERENCES regions(id), -- For sub-regions
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add region_id to locations table
ALTER TABLE locations 
ADD COLUMN IF NOT EXISTS region_id BIGINT REFERENCES regions(id);

-- Enable RLS for regions
ALTER TABLE regions ENABLE ROW LEVEL SECURITY;

-- Public read access for regions
CREATE POLICY "Public regions are viewable by everyone" 
ON regions FOR SELECT 
USING (true);

-- Authenticated insert/update/delete for regions (assuming admin usage)
-- For simplicity in this dev environment, we'll allow public write if needed, 
-- but sticking to the pattern:
CREATE POLICY "Enable insert for authenticated users only" 
ON regions FOR INSERT 
WITH CHECK (true); -- ideally auth.role() = 'authenticated'

CREATE POLICY "Enable update for authenticated users only" 
ON regions FOR UPDATE 
USING (true);

CREATE POLICY "Enable delete for authenticated users only" 
ON regions FOR DELETE 
USING (true);

-- Insert initial 13 States + 3 Federal Territories of Malaysia
INSERT INTO regions (name, code) VALUES
('Johor', 'JHR'),
('Kedah', 'KDH'),
('Kelantan', 'KTN'),
('Melaka', 'MLK'),
('Negeri Sembilan', 'NSN'),
('Pahang', 'PHG'),
('Perak', 'PRK'),
('Perlis', 'PLS'),
('Pulau Pinang', 'PNG'),
('Sabah', 'SBH'),
('Sarawak', 'SWK'),
('Selangor', 'SGR'),
('Terengganu', 'TRG'),
('Kuala Lumpur', 'KUL'),
('Labuan', 'LBN'),
('Putrajaya', 'PJY')
ON CONFLICT DO NOTHING; -- In case run multiple times (requires unique constraint which we haven't set, but this is safe enough for initial script if empty)

-- Add comment
COMMENT ON TABLE regions IS 'Malaysia States and Sub-regions';
