-- One core travel package can have multiple independently priced accommodations.
-- Apply this migration before deploying the Tioman options UI.

BEGIN;

CREATE TABLE IF NOT EXISTS public.travel_package_options (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  package_id bigint NOT NULL REFERENCES public.travel_packages(id) ON DELETE CASCADE,
  slug text NOT NULL,
  name_zh text NOT NULL,
  name_en text,
  accommodation_name text NOT NULL,
  accommodation_type text,
  village_name text,
  short_description text,
  suitable_for jsonb NOT NULL DEFAULT '[]'::jsonb,
  price_from numeric(12,2),
  price_currency text NOT NULL DEFAULT 'MYR',
  price_unit text NOT NULL CHECK (price_unit IN ('person', 'room', 'package', 'group')),
  price_display text NOT NULL,
  price_rows jsonb NOT NULL DEFAULT '[]'::jsonb,
  included_items jsonb NOT NULL DEFAULT '[]'::jsonb,
  excluded_items jsonb NOT NULL DEFAULT '[]'::jsonb,
  notes jsonb NOT NULL DEFAULT '[]'::jsonb,
  validity_label text,
  valid_until date,
  brochure_image jsonb,
  gallery jsonb NOT NULL DEFAULT '[]'::jsonb,
  whatsapp_message text,
  source_code text,
  featured boolean NOT NULL DEFAULT false,
  sort_order integer NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'archived')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (package_id, slug)
);

CREATE INDEX IF NOT EXISTS travel_package_options_package_idx
  ON public.travel_package_options (package_id, status, sort_order);

ALTER TABLE public.travel_package_options ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public can read active travel package options" ON public.travel_package_options;
CREATE POLICY "Public can read active travel package options"
ON public.travel_package_options FOR SELECT
USING (
  status = 'active'
  AND EXISTS (
    SELECT 1 FROM public.travel_packages package
    WHERE package.id = package_id AND package.status = 'published'
  )
);

DROP POLICY IF EXISTS "Authenticated can manage travel package options" ON public.travel_package_options;
CREATE POLICY "Authenticated can manage travel package options"
ON public.travel_package_options FOR ALL TO authenticated
USING (true) WITH CHECK (true);

INSERT INTO public.travel_packages (
  slug, title_zh, title_en, destination, region_id, duration,
  short_description, full_description, cover_image, highlights, suitable_for,
  itinerary_days, included_items, excluded_items, notes, price_display, price_note,
  whatsapp_message, source_code, status, featured, sort_order, seo_title,
  seo_description, canonical_url, related_location_ids, related_guide_slugs,
  related_note_slugs, affiliate_link_ids, published_at
)
SELECT
  'tioman-3d2n',
  '刁曼岛 3天2夜浮潜配套 2026',
  'Pulau Tioman 3D2N Snorkeling Package 2026',
  'Pulau Tioman, Pahang, Malaysia',
  legacy.region_id,
  '3天2夜',
  '刁曼岛 3天2夜浮潜配套提供多家 Resort 与不同预算选择，可根据人数、房型、出发日期和住宿偏好比较适合的方案。配套内容可能包括住宿、餐食、船票、浮潜或码头接送，具体项目以所选择的 Resort 为准。',
  '同一条刁曼岛 3天2夜浮潜路线可选择不同 Resort、房型与报价单位。价格会因 Resort、人数、房型、日期、船票和附加费用而不同；请选择住宿方案后查看详情，付款前以旅行社或 Resort 最终确认资料为准。',
  legacy.cover_image,
  '["3 家 Resort 可选择", "每人 RM509 起", "浮潜、船票与接送以所选 Resort 为准"]'::jsonb,
  '["预算型海岛小旅行", "情侣", "家庭", "朋友团体"]'::jsonb,
  '[{"title":"选择 Resort 与房型","summary":"比较 Paya Beach Resort、Aman Tioman Resort 和 The Barat Tioman 的价格单位、船票与住宿安排。"},{"title":"确认出发与浮潜安排","summary":"浮潜、船班、码头接送和 Resort 活动以所选方案、天气、海况与最终确认资料为准。"},{"title":"返程","summary":"退房与返程安排以旅行社或 Resort 最终确认资料为准。"}]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '["价格会因 Resort、人数、房型、日期、船票和附加费用而不同，请选择住宿方案后查看详情。", "所有价格、房况、船班、税费与活动安排以旅行社或 Resort 最终确认为准。"]'::jsonb,
  '每人 RM509 起',
  '价格会因 Resort、人数、房型、日期、船票和附加费用而不同，请选择住宿方案后查看详情。最终价格、房况、船班、税费与活动安排以旅行社或 Resort 最终确认为准。',
  E'你好，我从 JnQ Journey 看到刁曼岛 3天2夜浮潜配套，想请你们帮我比较适合的 Resort。\n\n预计日期：\n成人：\n儿童及年龄：\n预计预算：\n出发码头：\n偏好：\n其他要求：\n\n来源：JNQ-TIOMAN-COMPARE',
  'JNQ-TIOMAN-COMPARE',
  'draft', false, 20,
  '刁曼岛 3天2夜浮潜配套 2026｜酒店与价格比较｜JnQ Journey',
  '比较刁曼岛 Aman Tioman、Paya Beach Resort 与 The Barat Tioman 3天2夜配套，包括住宿、船票、餐食、浮潜、房型价格与附加费用。',
  'https://www.jnqjourney.com/packages/tioman-3d2n',
  ARRAY[]::bigint[], ARRAY[]::text[], ARRAY[]::text[], ARRAY[]::bigint[], NULL
FROM public.travel_packages legacy
WHERE legacy.slug IN ('tioman-aman-resort-3d2n', 'tioman-paya-beach-resort-3d2n', 'tioman-barat-resort-3d2n')
ORDER BY legacy.id
LIMIT 1
ON CONFLICT (slug) DO UPDATE SET
  title_zh = EXCLUDED.title_zh,
  title_en = EXCLUDED.title_en,
  destination = EXCLUDED.destination,
  region_id = EXCLUDED.region_id,
  duration = EXCLUDED.duration,
  short_description = EXCLUDED.short_description,
  full_description = EXCLUDED.full_description,
  cover_image = EXCLUDED.cover_image,
  highlights = EXCLUDED.highlights,
  suitable_for = EXCLUDED.suitable_for,
  itinerary_days = EXCLUDED.itinerary_days,
  included_items = EXCLUDED.included_items,
  excluded_items = EXCLUDED.excluded_items,
  notes = EXCLUDED.notes,
  price_display = EXCLUDED.price_display,
  price_note = EXCLUDED.price_note,
  whatsapp_message = EXCLUDED.whatsapp_message,
  source_code = EXCLUDED.source_code,
  status = 'draft',
  featured = false,
  sort_order = EXCLUDED.sort_order,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  canonical_url = EXCLUDED.canonical_url,
  published_at = NULL,
  updated_at = now();

WITH main_package AS (
  SELECT id FROM public.travel_packages WHERE slug = 'tioman-3d2n'
), legacy AS (
  SELECT * FROM public.travel_packages
  WHERE slug IN ('tioman-paya-beach-resort-3d2n', 'tioman-aman-resort-3d2n', 'tioman-barat-resort-3d2n')
)
INSERT INTO public.travel_package_options (
  package_id, slug, name_zh, name_en, accommodation_name, accommodation_type,
  village_name, short_description, suitable_for, price_from, price_currency,
  price_unit, price_display, price_rows, included_items, excluded_items, notes,
  validity_label, valid_until, brochure_image, gallery, whatsapp_message,
  source_code, featured, sort_order, status
)
SELECT
  main_package.id,
  CASE legacy.slug
    WHEN 'tioman-paya-beach-resort-3d2n' THEN 'paya-beach-resort'
    WHEN 'tioman-aman-resort-3d2n' THEN 'aman-tioman'
    ELSE 'the-barat-tioman'
  END,
  CASE legacy.slug
    WHEN 'tioman-paya-beach-resort-3d2n' THEN 'Paya Beach Resort'
    WHEN 'tioman-aman-resort-3d2n' THEN 'Aman Tioman Resort'
    ELSE 'The Barat Tioman'
  END,
  CASE legacy.slug
    WHEN 'tioman-paya-beach-resort-3d2n' THEN 'Paya Beach Resort'
    WHEN 'tioman-aman-resort-3d2n' THEN 'Aman Tioman Resort'
    ELSE 'The Barat Tioman'
  END,
  CASE legacy.slug
    WHEN 'tioman-paya-beach-resort-3d2n' THEN 'Paya Beach Resort'
    WHEN 'tioman-aman-resort-3d2n' THEN 'Aman Tioman Resort'
    ELSE 'The Barat Tioman'
  END,
  'resort', NULL, legacy.short_description, legacy.suitable_for,
  CASE legacy.slug WHEN 'tioman-paya-beach-resort-3d2n' THEN 509 WHEN 'tioman-aman-resort-3d2n' THEN 690 ELSE 1440 END,
  'MYR',
  CASE legacy.slug WHEN 'tioman-barat-resort-3d2n' THEN 'room' ELSE 'person' END,
  legacy.price_display,
  CASE legacy.slug
    WHEN 'tioman-paya-beach-resort-3d2n' THEN '[{"label":"2人1房","price":"RM649／成人"},{"label":"3人1房","price":"RM559／成人"},{"label":"4人1房","price":"RM509／成人"},{"label":"儿童（2–11岁）","price":"RM350／人"}]'::jsonb
    WHEN 'tioman-aman-resort-3d2n' THEN '[{"label":"2人1房","price":"RM790／成人"},{"label":"3人1房","price":"RM720／成人"},{"label":"4人1房","price":"RM690／成人"},{"label":"儿童（4–11岁）","price":"RM530／人"},{"label":"儿童（2–4岁）","price":"RM120／人"}]'::jsonb
    ELSE '[{"label":"Standard Chalet Garden View（双人）","price":"RM1,440／房"},{"label":"Standard Family Chalet Garden View（四人）","price":"RM2,290／房"},{"label":"Deluxe Family Room Pool+Part Seaview（四人）","price":"RM2,470／房"},{"label":"Seafront Room Seaview（双人）","price":"RM2,020／房"}]'::jsonb
  END,
  legacy.included_items, legacy.excluded_items, legacy.notes,
  CASE legacy.slug WHEN 'tioman-paya-beach-resort-3d2n' THEN '价格有效至 14 Nov 2026' WHEN 'tioman-aman-resort-3d2n' THEN '价格有效至 15 Nov 2026' ELSE 'Peak Season 2026' END,
  CASE legacy.slug WHEN 'tioman-paya-beach-resort-3d2n' THEN DATE '2026-11-14' WHEN 'tioman-aman-resort-3d2n' THEN DATE '2026-11-15' ELSE NULL END,
  legacy.gallery->0, legacy.gallery, legacy.whatsapp_message, legacy.source_code,
  false,
  CASE legacy.slug WHEN 'tioman-paya-beach-resort-3d2n' THEN 10 WHEN 'tioman-aman-resort-3d2n' THEN 20 ELSE 30 END,
  'active'
FROM legacy CROSS JOIN main_package
ON CONFLICT (package_id, slug) DO UPDATE SET
  name_zh = EXCLUDED.name_zh, name_en = EXCLUDED.name_en,
  accommodation_name = EXCLUDED.accommodation_name,
  accommodation_type = EXCLUDED.accommodation_type,
  village_name = EXCLUDED.village_name,
  short_description = EXCLUDED.short_description,
  suitable_for = EXCLUDED.suitable_for, price_from = EXCLUDED.price_from,
  price_currency = EXCLUDED.price_currency, price_unit = EXCLUDED.price_unit,
  price_display = EXCLUDED.price_display, price_rows = EXCLUDED.price_rows,
  included_items = EXCLUDED.included_items, excluded_items = EXCLUDED.excluded_items,
  notes = EXCLUDED.notes, validity_label = EXCLUDED.validity_label,
  valid_until = EXCLUDED.valid_until, brochure_image = EXCLUDED.brochure_image,
  gallery = EXCLUDED.gallery, whatsapp_message = EXCLUDED.whatsapp_message,
  source_code = EXCLUDED.source_code, featured = EXCLUDED.featured,
  sort_order = EXCLUDED.sort_order, status = 'active', updated_at = now();

DELETE FROM public.travel_packages
WHERE slug IN ('tioman-aman-resort-3d2n', 'tioman-paya-beach-resort-3d2n', 'tioman-barat-resort-3d2n');

COMMIT;
