-- Fresh-project bootstrap for JnQ Journey
-- Run this first in a brand new Supabase project.

BEGIN;

CREATE TABLE IF NOT EXISTS regions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  name_cn TEXT,
  code TEXT,
  country TEXT,
  parent_id BIGINT REFERENCES regions(id) ON DELETE SET NULL,
  description TEXT,
  image_url TEXT,
  bounds JSONB,
  slug TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  name_cn TEXT,
  category TEXT DEFAULT 'attraction',
  address TEXT,
  latitude DOUBLE PRECISION NOT NULL,
  longitude DOUBLE PRECISION NOT NULL,
  region_id BIGINT REFERENCES regions(id) ON DELETE SET NULL,
  video_url TEXT,
  facebook_video_url TEXT,
  image_url TEXT,
  images TEXT[] DEFAULT '{}',
  description TEXT,
  review TEXT,
  tags TEXT[] DEFAULT '{}',
  visit_date DATE,
  opening_hours JSONB,
  price_info JSONB,
  google_maps_url TEXT,
  status TEXT DEFAULT 'active',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_locations_region_id ON locations(region_id);
CREATE INDEX IF NOT EXISTS idx_locations_category ON locations(category);
CREATE INDEX IF NOT EXISTS idx_locations_status ON locations(status);
CREATE INDEX IF NOT EXISTS idx_regions_parent_id ON regions(parent_id);
CREATE INDEX IF NOT EXISTS idx_regions_country ON regions(country);

ALTER TABLE regions ADD COLUMN IF NOT EXISTS name_cn TEXT;
ALTER TABLE regions ADD COLUMN IF NOT EXISTS code TEXT;
ALTER TABLE regions ADD COLUMN IF NOT EXISTS country TEXT;
ALTER TABLE regions ADD COLUMN IF NOT EXISTS parent_id BIGINT REFERENCES regions(id) ON DELETE SET NULL;
ALTER TABLE regions ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE regions ADD COLUMN IF NOT EXISTS image_url TEXT;
ALTER TABLE regions ADD COLUMN IF NOT EXISTS bounds JSONB;
ALTER TABLE regions ADD COLUMN IF NOT EXISTS slug TEXT;
ALTER TABLE regions ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE regions ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

ALTER TABLE locations ADD COLUMN IF NOT EXISTS name_cn TEXT;
ALTER TABLE locations ADD COLUMN IF NOT EXISTS category TEXT DEFAULT 'attraction';
ALTER TABLE locations ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE locations ADD COLUMN IF NOT EXISTS region_id BIGINT REFERENCES regions(id) ON DELETE SET NULL;
ALTER TABLE locations ADD COLUMN IF NOT EXISTS video_url TEXT;
ALTER TABLE locations ADD COLUMN IF NOT EXISTS facebook_video_url TEXT;
ALTER TABLE locations ADD COLUMN IF NOT EXISTS image_url TEXT;
ALTER TABLE locations ADD COLUMN IF NOT EXISTS images TEXT[] DEFAULT '{}';
ALTER TABLE locations ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE locations ADD COLUMN IF NOT EXISTS review TEXT;
ALTER TABLE locations ADD COLUMN IF NOT EXISTS tags TEXT[] DEFAULT '{}';
ALTER TABLE locations ADD COLUMN IF NOT EXISTS visit_date DATE;
ALTER TABLE locations ADD COLUMN IF NOT EXISTS opening_hours JSONB;
ALTER TABLE locations ADD COLUMN IF NOT EXISTS price_info JSONB;
ALTER TABLE locations ADD COLUMN IF NOT EXISTS google_maps_url TEXT;
ALTER TABLE locations ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'active';
ALTER TABLE locations ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE locations ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

CREATE OR REPLACE FUNCTION update_generic_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_update_locations_updated_at ON locations;
CREATE TRIGGER trigger_update_locations_updated_at
BEFORE UPDATE ON locations
FOR EACH ROW
EXECUTE FUNCTION update_generic_updated_at();

DROP TRIGGER IF EXISTS trigger_update_regions_updated_at ON regions;
CREATE TRIGGER trigger_update_regions_updated_at
BEFORE UPDATE ON regions
FOR EACH ROW
EXECUTE FUNCTION update_generic_updated_at();

ALTER TABLE locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE regions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Enable read access for all users" ON locations;
DROP POLICY IF EXISTS "Enable insert access for all users" ON locations;
DROP POLICY IF EXISTS "Enable update access for all users" ON locations;
DROP POLICY IF EXISTS "Enable delete access for all users" ON locations;

CREATE POLICY "Enable read access for all users"
ON locations FOR SELECT
USING (true);

CREATE POLICY "Enable insert access for all users"
ON locations FOR INSERT
WITH CHECK (true);

CREATE POLICY "Enable update access for all users"
ON locations FOR UPDATE
USING (true);

CREATE POLICY "Enable delete access for all users"
ON locations FOR DELETE
USING (true);

DROP POLICY IF EXISTS "Public regions are viewable by everyone" ON regions;
DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON regions;
DROP POLICY IF EXISTS "Enable update for authenticated users only" ON regions;
DROP POLICY IF EXISTS "Enable delete for authenticated users only" ON regions;

CREATE POLICY "Public regions are viewable by everyone"
ON regions FOR SELECT
USING (true);

CREATE POLICY "Enable insert for authenticated users only"
ON regions FOR INSERT
WITH CHECK (true);

CREATE POLICY "Enable update for authenticated users only"
ON regions FOR UPDATE
USING (true);

CREATE POLICY "Enable delete for authenticated users only"
ON regions FOR DELETE
USING (true);

COMMIT;
